### ISSUE TITLE
Input Dialog Enhancement

### ISSUE THREAD

**Issue by samsonchen** [tracmo/open-tls-iot-client#2]
In the settings menu, some dialog box may be overlaid by the keypads:

![IMG_8035](https://user-images.githubusercontent.com/3621956/106859348-e0404700-66fd-11eb-91d8-6418c3b3639b.PNG)
![IMG_8036](https://user-images.githubusercontent.com/3621956/106859363-e3d3ce00-66fd-11eb-89d5-121628dfba9f.PNG)

**Comment by janeric11github** [comment]
Implemented on 7f5c3ad3d3c2184323de7f8942f849e10ec40711
